/**
 * Represents the final outcome of the video compression phase.
 * All properties are readonly to enforce immutability.
 */
export interface CompressionResult {
  readonly originalFile: File;
  readonly processedFile: File;
  readonly compressionUsed: boolean;
  readonly originalSize: number;
  readonly processedSize: number;
  readonly bytesSaved: number;
  readonly compressionRatio: number;
  readonly compressionTimeMs: number;
  readonly fallbackReason?: string;
  readonly ffmpegInitialized: boolean;
  readonly ffmpegLoadTimeMs: number;
  readonly ffmpegVersion?: string;
}

/**
 * Pure utility class responsible for formatting and logging the outcome of a video upload.
 * It does not modify state or perform any upload logic.
 */
export class UploadSummaryLogger {
  /**
   * Prints the final UPLOAD SUMMARY to the console.
   * 
   * @param result - The immutable CompressionResult generated by VideoProcessingService.
   * @param cloudinaryUrl - The final Cloudinary or storage URL, if applicable.
   */
  static printSummary(result: CompressionResult, cloudinaryUrl: string | null): void {
    const origMb = (result.originalSize / (1024 * 1024)).toFixed(2);
    const procMb = (result.processedSize / (1024 * 1024)).toFixed(2);
    const savedMb = (result.bytesSaved / (1024 * 1024)).toFixed(2);
    const timeSec = (result.compressionTimeMs / 1000).toFixed(2);

    console.log(`
UPLOAD SUMMARY
---------------
Original Size: ${origMb} MB
Compressed Size: ${procMb} MB
Compression Saved: ${savedMb} MB
Compression Time: ${result.compressionTimeMs > 0 ? timeSec + 's' : '0s'}
Uploaded File: ${result.compressionUsed ? 'Compressed' : 'Original'}
Compression Used: ${result.compressionUsed ? 'YES' : 'NO'}
Fallback Reason: ${result.fallbackReason || 'None'}
Cloudinary Public ID: ${cloudinaryUrl || 'Failed'}
    `);
  }
}
